### ISSUE TITLE
what happened with the existing `--` operator?

### ISSUE THREAD

**Issue by ferigis** [Pouriya-Jahanbakhsh/pipeline#1]
Erlang already has that operator in order to subtract elements in a list 

```erlang
1> [1, 2, 3] -- [1].
[2,3]
```

**Comment by Pouriya-Jahanbakhsh** [comment]
In my experiences in some code reviews in some big or small projects like Ejabberd, ... . Erlang developers often don't like to use `--` operator in produnction env. (at least in main parts of code which should be run for many times). so when you include this lib's header file, Only you can just use `--` operator in tuples, lists or maps for seeing difference of two lists.  
example:
```erlang
...
-include_lib("pipeline/include/pipeline).

test() ->
    {Diff} = {[1,2,3] -- [1]}. % Diff = [2,3]
```
technically in compile time, it does not search in tuples, lists, maps for pipelining.

**Comment by Pouriya-Jahanbakhsh** [comment]
I'm still working on new library which supports pipeline and other function compositions.
For example writing:
```erlang
?bool_exec( a() -- b() -- c() )
```
will equal to writing
```erlang
case a() of
    true ->
        case b() of
            true ->
                c();
            false ->
                false
        end;
    false ->
        false
end.
```
or writing:
```erlang
?ok_pipeline( a() -- b() -- c() )
```
will equal to writing:
```erlang
case a() of
    {ok, Result1} ->
        case b(Result1) of
            {ok, Result2} ->
                c(Result2);
            {error, _}=Err ->
                Err
        end;
    {error, _}=Err ->
        Err
end.
```
If you need just pipelining, use this and you cant use `--` operator with its default usage in every place. In next library which supports pipeline too, i will push it in a macro like `?pipeline`, then you can use `--` operator outside of that macro with its default usage.
