### ISSUE TITLE
Railway oriented programming

### ISSUE THREAD

**Issue by hengestone** [Pouriya-Jahanbakhsh/pipeline#4]
Hi Pouriya,

Looking at oltarasenko/epipe there is an interesting way to implement railway oriented programming (https://fsharpforfunandprofit.com/rop/), namely to have 3 versions of a function like this:

`myfunc(arg1, arg2) ->
  body.
`
and then adding 2 versions:
`myfunc({ok, {arg1, arg2}}) -> myfunc(arg1, arg2);` 
and
`myfunc({error, _} = ErrArg) -> ErrArg;`
 
So that if you do `myfunc(arg1, arg2) |> myfunc2(arg1, arg2) |> myfync3(arg)` you would get either the output of the last function or the error message from the function that failed.

Would it be possible to implement the code to create those 2 function headers in the parse transform?

**Comment by Pouriya-Jahanbakhsh** [comment]
Hi. Generally speaking I'm interested in parse transformation. I think we can, but also we need to check if these function are exist or not. Also we need execute them, then we need replace ... |> ... with some code which executes these functions.
